### PR TITLE
Cast Added to Line 224

### PR DESCRIPTION
**Pull request by hcuffy**

### CODE REVIEW

**Comment by jtnelson** [comment]
Do the following, so that the deletion of the launch files isn't committed

```bash
$ git revert b13fcae26212c64403ea33302e6c1cdd508835ee
```
Then add the cast again, but this time only commit AccessManager.java

**Comment by hcuffy** [comment]
I'm getting this:

MacBook-Pro-2:concourse cuffyhenry$ git revert 
b13fcae26212c64403ea33302e6c1cdd508835ee
error: Your local changes would be overwritten by revert.
hint: Commit your changes or stash them to proceed.
fatal: revert failed
MacBook-Pro-2:concourse cuffyhenry$

**Comment by jtnelson** [comment]
Do
```bash
$ git stash
```
and then revert


*JEFF NELSON*
Founder & CEO | Cinchapi Inc.
www.cinchapi.com

Follow us on Twitter <https://twitter.com/cinchapi> | Github
<https://github.com/cinchapi> | AngelList <https://angel.co/cinchapi>

**Comment by hcuffy** [comment]
I'm suppose to go:

git add 
concourse-server/src/main/java/org/cinchapi/concourse/security/AccessManager.java

git commit -m "change to accessmanger"

correct?

**Comment by jtnelson** [comment]
Just do gir commit directly on the file instead of doing git add in a separate step 

Sent from my iPhone




On Mon, Oct 5, 2015 at 10:19 AM -0700, "Henry Cuffy" <notifications@github.com> wrote:










I'm suppose to go:



git add 

concourse-server/src/main/java/org/cinchapi/concourse/security/AccessManager.java



git commit -m "change to accessmanger"



correct?

**Comment by hcuffy** [comment]
this is what I get:

MacBook-Pro-2:concourse cuffyhenry$ git commit 
concourse-server/src/main/java/org/cinchapi/concourse/security/AccessManager.java
On branch develop
Your branch is up-to-date with 'origin/develop'.
nothing to commit, working directory clean
MacBook-Pro-2:concourse cuffyhenry$

**Comment by jtnelson** [comment]
Do git log and see if the commit to revert the previous one is there

**Comment by hcuffy** [comment]
most recent:

commit b13fcae26212c64403ea33302e6c1cdd508835ee
Author: Henry Cuffy 
<cuffyhenry@MacBook-Pro-2.Speedport_W723_V_Typ_A_1_01_010>
Date:   Mon Oct 5 18:46:44 2015 +0200

     Cast Added to Line 224

**Comment by jtnelson** [comment]
You'll need to git stash and then git revert the latest commit. Then make the change to AccessManager.java again and commit only that file

**Comment by hcuffy** [comment]
Hey Jeff thanks for helping because it must be frustrating. I’m going to tackle this in the morning with some fresh eyes.

**Comment by jtnelson** [comment]
No worries! I'm happy to help, so reach out tomorrow when you're ready and
we can pick up and get this finished :)


*JEFF NELSON*
Founder & CEO | Cinchapi Inc.
www.cinchapi.com

Follow us on Twitter <https://twitter.com/cinchapi> | Github
<https://github.com/cinchapi> | AngelList <https://angel.co/cinchapi>

**Pull request merged**
